# Generated by Django 4.2.4 on 2023-09-01 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_item_discount_price_alter_item_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(default='This is test description'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='discount_price',
            field=models.FloatField(blank=True, null=True, verbose_name='Цена со скидкой'),
        ),
    ]
